
services:

  frontend:
    build: ./WebApp/Frontend/
    ports:
      - "5173:5173"
    volumes:
      - ./WebApp/Frontend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./WebApp/Backend
    ports:
      - "8000:8000"
    volumes:
      - ./WebApp/Backend:/app

  extension:
    build: ./CSC_Extension/
    volumes:
      - ./CSC_Extension:/app
