version: "3.9"

services:

  frontend:
    build: ./WebApp/Frontend/
    ports:
      - "5173:5173"
    volumes:
      - ./WebApp/Frontend/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./WebApp/Backend
    ports:
      - "8000:8000"
    volumes:
      - ./WebApp/Backend:/app

  extension:
    build: ./WebExtension/svelte/svelte-app
    command: ["npm", "run", "build"]
    volumes:
      - ./WebExtension/svelte/svelte-app:/app
